### ISSUE TITLE
Add legend for progress bars

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#24]
For 'rural' and 'urban' only
<img width="216" alt="image" src="https://user-images.githubusercontent.com/737638/154216600-b95287b8-902d-4c8f-bd84-4f16da6a6d86.png">

**Comment by dhowe** [comment]
I think we may need more information here. It is rather bit opaque what the bands are doing as is

**Comment by shadoof** [comment]
We can add this to documentation. How about:

The bands around the sentences of _Preoccupations_ indicate their real-time affinities with its two underlying rural-contemplative and urban-conflict-riven compositions. The outer band shows the percentage of _changeable_ words which belong to one or other text. The gap in this band represents words which are _similars_ but which belong to neither composed text. This gap grows as _Preoccupations_ ventures away from its current urban or rural domain and shrinks as it returns toward whichever domain is current. Urban and rural measures both have the top of their circle as their origin with rural’s increasing clockwise and urban’s anti-clockwise. The inner band shows, for each domain, the overall percentage of words from the two composed texts. Since the compositions share many words rural and urban measures always overlap, with the purple region indicating the real-time extent of this overlap.

**Comment by dhowe** [comment]
I think this is good for the documentation, but for those who see the work first, it will still be quite confusing

**Comment by dhowe** [comment]
as discussed, let's add a toggle for the inner bar, then decide whether to hide it or not
