### ISSUE TITLE
Warning on font load (chrome)

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#70]
WARNING:
> _The resource http://localhost/git/ramble/fonts/Source_Serif_Pro/source-serif-pro-v15-latin-regular.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally._

**Comment by dhowe** [comment]
@shadoof said:

> Do we need the the <link> preloads in the index.html file? These cause the warnings and I thought the @font-face in style.css does same thing (I removed links locally and this had not ill effects). woff2 in style.css should come before woff (so it is preferred)

**Comment by dhowe** [comment]
I believe, correct me if I'm wrong @Real-John-Cheung, that this is to make sure the font is loaded before the initial measuring of words for the starting layout,  without which we will sometimes get incorrect measurements and a non-optimal or just broken layout, depending on the user's font set

**Comment by Real-John-Cheung** [comment]
yes, because is quite essential for the algorithm that the font is loaded before dom tree is rendered, normally @font-face would do, but in some cases (especially when the client's network speed is slow) no. Therefore we need the preload tag. 
And for the warning, I think it is quite confusing... so if we preload font, this warning will always appear even if we do use the font in css (i believe that is some weird problems with font file only )
