### ISSUE TITLE
Create high-res screenshot of interface

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#88]
need 2 nice high-res ( >= 2000x2000) screenshots, one for rural, one with urban (from which I will create a dark version)

**Comment by shadoof** [comment]
honestly not exactly sure what it is you want here

**Comment by dhowe** [comment]
just two screenshots, one with rural, one with urban... are you asking about how to get the urban text up?

**Comment by shadoof** [comment]
Do you mean, screen shot each of them:
-  from the working sketch?
- with the visualization showing, e.g. blue but no red and then red but no blue? (and no purple for either)
- and I guess, yes, I don't know how to get the urban text up?
- and you want me to hack the code to stop or pause it with *all* of each text showing, as composed, and the appropriate visualization to affirm the state of the texts?

Thinking about this, perhaps the piece, as it opens in 'rural' should just open with the band showing that appropriate portions of blue and light green? (rather than the light gray)
Or better:
- open/refresh -> band is light grey, reader has not started
- wait 2-3 seconds
- reader starts and band goes blue and light green
- wait for `readDelay`
- start update, etc. ...

**Comment by dhowe** [comment]
Steps:

- [ ] Take 4k screenshot with color bars and reader (as below)
- [ ] Swap urban and rural texts temporarily in code
- [ ] Take 2nd 4k  screenshot with color bars and reader

<img width="725" alt="Screenshot 2022-05-22 at 5 13 11 PM" src="https://user-images.githubusercontent.com/737638/169688161-4db4fb59-8642-480e-b018-4d46e0129030.png">

**Comment by Real-John-Cheung** [comment]
previews:
![4k_urban_domain](https://user-images.githubusercontent.com/61215358/169689507-c9ab295d-ac0b-47fe-bca2-3c13de2d1221.png)
![4k_rural_domain](https://user-images.githubusercontent.com/61215358/169689511-d5101412-f0c9-4ede-977a-ef3715d4dbff.png)

**Comment by dhowe** [comment]
perfect
